# Generated by Django 2.2.6 on 2023-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('client_ip', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'log_table',
            },
        ),
    ]
